### ISSUE TITLE
Pressing "back" breaks the site

### ISSUE THREAD

**Issue by ograycode** [ask-izzy/ask-izzy#588]
**What**: When you click on a service that you need, then press ok, if you decide to back out of it by going back a page ok doesn't work anymore.

**Steps to reproduce**: Go to the site, press a category. The next screen tells you that your information is private, press ok. On the next screen, press back. The ok button no longer works.

**Work around**: Back all the way out to the homepage and press the category again.

**Comment by DanielHeath** [comment]
Is this the browser back, or the left-pointing chevron at the top-left?

**Comment by DanielHeath** [comment]
Oh wow, just tested both and I see what you mean!

**Comment by ograycode** [comment]
@DanielHeath I was using browser back.

**Comment by DanielHeath** [comment]
Right - the code that disables the 'next' button until you enter a valid location isn't getting reset when navigating via 'back'.

**Comment by DanielHeath** [comment]
Fixed in https://github.com/ask-izzy/ask-izzy/pull/589
